### ISSUE TITLE
Unresolvable dependency

### ISSUE THREAD

**Issue by abelschooleman** [statikbe/laravel-nova-chained-translation-manager#7]
I installed this package in a project but I get the following error:
`Unresolvable dependency resolving [Parameter #2 [ <required> string $path ]] in class Statikbe\\LaravelChainedTranslator\\ChainedTranslationManager`
Any suggestions what might be the cause of this?

**Comment by sten** [comment]
@abelschooleman I just setup a fresh laravel+nova project with the library, but I do not get any errors. At which point during the installation do you get this error? Which version of Laravel are you using? Any extra info would be useful.

The `$path` var is the path to the custom language directory, which you can set in the config file. Did you try to publish the configuration and edit that?

**Comment by abelschooleman** [comment]
The package installs successfully and I published both the config of laravel-nova-chained-translation-manager and laravel-chained-translator. Not sure whether the latter is necessary but the result is the same. I haven't touched the config contents.
This error occurs as soon as I hit the package route in Nova (/nova/translation-manager).

The lang-custom directory is created under /resources including a .gitignore file so that seems to be working correctly.

Laravel version is 7.30.4 and Nova is 3.22.0.

**Comment by abelschooleman** [comment]
@sten I've got:
statikbe/laravel-chained-translator               1.1.0             
statikbe/laravel-nova-chained-translation-manager 1.2.2

I cleared the cache but that didn't help.

**Comment by abelschooleman** [comment]
@sten I just did a clean install of Laravel and Nova, Added this package and got the same error.

Also, I noticed in the documentation it says to use Statik\NovaTranslationManager\TranslationManager.
But the namespace for this file is Statikbe\NovaTranslationManager.

**Comment by Sonicelo** [comment]
Hi, I have just added this to my existing project and got the same problem.
Using laravel 8.34 and Nova 3.22.

**Comment by wdarins** [comment]
same problem here

**Comment by sten** [comment]
Sorry for the delay! Somehow my notifications on this repository were messed up. 

I just installed the version @Sonicelo mentioned, and I also get the error. I did some debugging and it appears something changed in Nova. The ChainedTranslationManager is injected into the TranslationController when you hit the `/nova-vendor/translation-manager/translations/` route.

The problem is that Nova does not load the complete service container on this route. So the singleton that is defined in the service provider of the chained translator is not loaded. This seems to be a Nova bug. I am looking for a workaround...

**Comment by sten** [comment]
@wdarins, @Sonicelo, @abelschooleman I just released a fix, so update to v1.3.0. Let me know if you still experience trouble!

The issue was in the way the dependencies were loaded on the service container. Nova tool routes now appear to no longer load all dependencies, so I fixed the TranslationServiceProvider so that it can be lazy loaded, and also optimised the order of the dependencies so it loads all dependencies.
